configurations:
  - transformer.yaml
resources:
  - gitrepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: arkime-ek-values
    behavior: create
    files:
    - values.yaml=values.yaml
