---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: arkime-ek
  namespace: arkime-ek
spec:
  interval: 5m
  path: "./kustomizations/arkime-ek"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hncd-demo-zarf-package
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: arkime-ek
      name: arkime-ek
  timeout: 5m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
      DOMAIN: "###ZARF_VAR_DOMAIN###"