---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bigbang
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations/bigbang"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hncd-demo-zarf-package
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: bigbang
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-creds
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
      DOMAIN: "###ZARF_VAR_DOMAIN###"
      ES_REPLICAS: "###ZARF_VAR_ES_REPLICAS"