---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hncd-demo-zarf-package
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/hncd-demo-zarf-package.git
  ref:
    branch: flux-bb-pkg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations/kubevirt"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hncd-demo-zarf-package
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: kubevirt
      name: kubevirt
  timeout: 5m
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
