---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hncd-demo-zarf-package
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/hncd-demo-zarf-package.git
  ref:
    branch: flux-bb-pkg