apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arkime3-viewer
  namespace: arkime
spec:
  targetNamespace: arkime
  releaseName: arkime3-viewer
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: "."
      sourceRef:
        kind: GitRepository
        name: arkime3-viewer
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: ek
      namespace: bigbang
  values:
    viewer_url: arkime.${DOMAIN}
